# Generated by Django 4.2.14 on 2024-09-10 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_book_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='submitted_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
